/** @type {import('next').NextConfig} */
const nextConfig = {};

const extraArray = [
  "www.coolmathgames.com",
      "www.gameinformer.com",
      "www.formula1.com",
      "store-images.s-microsoft.com",
      "lumiere-a.akamaihd.net",
      "sonicthehedgehog.com",
      "dosgames.com",
      "tfwiki.net",
      "www.tradergames.fr",
      "www.zelda.com",
      "media-cldnry.s-nbcnews.com",
      "www.konami.com",
      "imageio.forbes.com",
      "oldpcgaming.net",
      "sm.ign.com",
      "static.tweaktown.com",
      "media.spokesman.com",
      "www.denofgeek.com",
      "pisces.bbystatic.com",
      "www.golfdigest.com",
      "www.lukiegames.com",
      "pisces.bbystatic.com  ",
      "www.pokemon.com",
      "uploads.golmedia.net",
      "classicreload.com",
      "i.ebayimg.com",
      "umiere-a.akamaihd.net",
      "3.bp.blogspot.com",
      "media.gamestats.com",
      "www.hardcoregaming101.net",
      "thehoganreviews.files.wordpress.com",
      "now.estarland.com",
      "www.myabandonware.com",
      "teambuilding.com",
      "mario.wiki.gallery",
      "d3b4yo2b5lbfy.cloudfront.net",
      "www.lego.com",
      "www.wired.com",
      "i.redd.it",
      "cdn.arstechnica.net",
      "assets.bwbx.io",
      "images.gog-statics.com",
      "gamingpastime.com",
      "www.golfdigest.com",
      "assets.reedpopcdn.com",
      "images.nintendolife.com",
      "cdn.shopify.com",
      "media.contentapi.ea.com",
      "variety.com",
      "media.gq.com",
      "gamingtrend.com",
      "www.gran-turismo.com",
      "www.giantbomb.com",
      "i.guim.co.uk",
      "i0.wp.com",
      "cf.geekdo-images.com",
      "images.sftcdn.net",
      "i.987967.xyz",
      "gamefaqs.gamespot.com",
      "downloads.2kgames.com",
      "now.estarland.com",
      "www.vgchartz.com",
      "www.si.com",
      "classicreload.com",
      "blz-contentstack-images.akamaized.net",
      "mario.wiki.gallery",
      "wowroms-photos.com",
      "gamingtrend.com",
      "static01.nyt.com",
      "www.androidauthority.com",
      "assets.gamingintelligence.com ",
      "static0.gamerantimages.com",
      "ae01.alicdn.com",
      "www.retroplace.com",
      "www.zelda.com  ",
      "www.konami.com ",
      "fs-prod-cdn.nintendo-europe.com",
      "www.mobygames.com",
      "gamefabrique.com",
      "blog.activision.com",
      "data.gameflare.com",
      "i.pcmag.com ",
      "ms.yugipedia.com",
      "media.gamestats.com",
      "media.contentapi.ea.com",
      "news.xbox.com",
      "pcmedia.gamespy.com",
      "s3.amazonaws.com",
      "wz2100.net",

];

module.exports = {
  reactStrictMode: true,
  images: {
    domains: [
      "cdn.wikimg.net",
      "loderunnerwebgame.com",
      "archive.org",
      "assets-eu-01.kc-usercontent.com",
      "media.gamestop.com",
      "www.nme.com",
      "static1.gamespot.com",
      "images.blz-contentstack.com",
      "i.ytimg.com",
      "i.pcmag.com",
      "m.media-amazon.com",
      "archives.bulbagarden.net",
      "assets.pokemon.com",
      "upload.wikimedia.org",
      "assets.nintendo.com",
      "uk.cdromance.com",
      "images.crazygames.com",
      "i0.wp.com",
      "www.commonsensemedia.org",
      "cdn2.unrealengine.com",
      "static.wikia.nocookie.net",
      "play-lh.googleusercontent.com",
      "cdn.akamai.steamstatic.com",
      "www.callofduty.com",
      "media.wired.com",
      "oyster.ignimgs.com",
      "www.gran-turismo.com",
      "dynaimage.cdn.cnn.com",
      "www.kingdomhearts.com",
      "cdn.cloudflare.steamstatic.com",
      "media.wired.co.uk",
      "s3.amazonaws.com",
      "play-lh.googleusercontent.com",
      "www.smashbros.com",
      "www.gamespot.com",
      "cdn.vox-cdn.com",
      "gamespot.com",
      "static.wikia.nocookie.net",
      "www.nintendoworldreport.com",
      "0.wp.com",
      "static.metacritic.com",
      "assets.xboxservices.com",
      "assets-prd.ignimgs.com",
      "i.guim.co.uk",
      "images.launchbox-app.com",
      "assets1.ignimgs.com",
      "hardcore-gamer.s3.amazonaws.com",
      "assets.gamingintelligence.com",
      "dsmedia.ign.com",
      "cdn1.epicgames.com",
      "image.api.playstation.com",
      
    ],
  },
};
